### ISSUE TITLE
As a banned reporter I should be able to browse my previously reported issues.

### ISSUE THREAD

**Issue by Kmalynss** [Kotany-IF070-WebUI-RoR/NewVasjuky#44]
In other words, banned user should be able to login, and only creation of new issues should not be allowed.

**Comment by igorkasyanchuk** [comment]
use before_action :require_active_user (new method need to be added)
+ check if views `if user.active?`

**Comment by TarasBardiuk** [comment]
@igorkasyanchuk, what do you think about this?
- before_action in IssuesController calls new private method which checks if user is banned and if he is, redirects him to root_path with error message
- in header (view) we use if statement with helper_method from ApplicationController which checks if user is banned and if he is, we show him attention message, so he would see it in every page of the site.

**Comment by igorkasyanchuk** [comment]
create method in application_controller

```
before_action :require_active_user

def require_active_user
if current_user && current_user.banned?
  redirect_to root_path, notice: 'you dont have access....'
end
end
```
it will call this for any request

And in HomeController (or what you have for root_path) you can do followin

```
class HomeController
  skip_before_action :require_active_user
```

**Comment by TarasBardiuk** [comment]
@igorkasyanchuk, yes-yes, I understand it. But first @Kmalynss said that we need to block only the creation of issues, and you propose to block everything except the homepage. In my opinion it's better to block only the creation of issues, because in your version banned user couldn't get access to his earlier submitted issues and, correct me if I'm wrong, the app will call request in every page to check if the user is banned instead of check it only if he want to write a new issue.
And what do you think about "eternal" message about blocking in header, do we need show him it?

**Comment by igorkasyanchuk** [comment]
on my opinion bad guys should be redirected from all request and automatically logged out
this is OK, otherwise you need to check banned users in many other places like adding comments, added ratings, etc

I would just go and implement it this way. this is not important functionality and NOT THE CORE of what you are doing on this project
